# Generated by Django 5.2.1 on 2025-05-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('order_id', models.CharField(max_length=100)),
                ('amount_sgd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_id', models.CharField(max_length=100)),
            ],
        ),
    ]
