# Generated by Django 5.2.1 on 2025-05-12 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_importedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='imported_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='core.importedfile'),
        ),
    ]
